#指定对应的端口号
server:
  port: 8762

#配置Eureka Client
eureka:
  client:
    service-url:
      #服务中心地址
      defaultZone: http://localhost:8761/eureka/
  instance:
    #是否启用Ip注册方式，开启后服务实例变为IP地址，更便于找到对应服务提供者的主机
    prefer-ip-address: true
    #服务实例ID格式
    instance-id: ${spring.application.name}.${spring.cloud.client.ip-address}:${server.port}
#配置服务名
spring:
  application:
    name: eureka-client-service
